import React, { useState } from 'react';
import { ArrowLeftRight, CheckCircle2, XCircle, Clock, Truck, ShieldAlert, DollarSign } from 'lucide-react';
import { INITIAL_TRANSFERS } from '../../../data/mockAppData';
import { RedistributionTransfer } from '../../../types';

export const CrossStateRedistribution: React.FC = () => {
  const [transfers, setTransfers] = useState<RedistributionTransfer[]>(
    (INITIAL_TRANSFERS || []).filter((t) => t.tier === 'INTER_STATE')
  );
  const [message, setMessage] = useState<string | null>(null);

  const handleApprove = (id: string) => {
    setTransfers(
      transfers.map((t) =>
        t.id === id ? { ...t, status: 'APPROVED', approvedBy: 'National Health Officer' } : t
      )
    );
    setMessage('Transfer approved and dispatch order routed to State Central Depots!');
    setTimeout(() => setMessage(null), 3000);
  };

  const handleReject = (id: string) => {
    setTransfers(transfers.map((t) => (t.id === id ? { ...t, status: 'REJECTED' } : t)));
    setMessage('Transfer request rejected.');
    setTimeout(() => setMessage(null), 3000);
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-10" id="cross-state-redistribution-screen">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900 border border-slate-800 rounded-xl p-6">
        <div>
          <h1 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <ArrowLeftRight className="w-5 h-5 text-blue-400" />
            Cross-State Redistribution Queue
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Evaluate, authorize, or reject inter-state emergency drug redistribution recommendations generated by the national AI logistics engine.
          </p>
        </div>
      </div>

      {message && (
        <div className="p-4 bg-emerald-950/80 border border-emerald-700/60 rounded-lg text-emerald-300 text-sm flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          {message}
        </div>
      )}

      {/* Transfer cards */}
      <div className="space-y-4">
        {transfers.map((transfer) => (
          <div
            key={transfer.id}
            className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4 hover:border-slate-700 transition-all shadow-sm"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
              <div className="flex items-center gap-3">
                <span className="font-mono text-xs font-bold text-blue-400 bg-blue-950/60 border border-blue-800 px-2.5 py-1 rounded">
                  {transfer.transferNumber}
                </span>
                <span
                  className={`px-2 py-0.5 rounded text-xs font-semibold border ${
                    transfer.urgency === 'EMERGENCY'
                      ? 'bg-red-950/70 border-red-800 text-red-300'
                      : 'bg-amber-950/70 border-amber-800 text-amber-300'
                  }`}
                >
                  {transfer.urgency}
                </span>
              </div>

              <div className="flex items-center gap-3 text-xs">
                <span className="text-slate-400">Created: {transfer.createdAt}</span>
                <span
                  className={`px-2 py-0.5 rounded font-medium border ${
                    transfer.status === 'APPROVED'
                      ? 'bg-emerald-950/60 text-emerald-400 border-emerald-800'
                      : transfer.status === 'REJECTED'
                      ? 'bg-red-950/60 text-red-400 border-red-800'
                      : 'bg-amber-950/60 text-amber-300 border-amber-800'
                  }`}
                >
                  {transfer.status.replace('_', ' ')}
                </span>
              </div>
            </div>

            {/* Source to Destination */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center bg-slate-950/80 p-4 rounded-lg border border-slate-800">
              <div>
                <div className="text-[11px] uppercase tracking-wider text-slate-500 font-semibold">Origin Warehouse (Surplus)</div>
                <div className="text-sm font-semibold text-slate-200 mt-1">{transfer.sourceFacility}</div>
              </div>

              <div className="flex flex-col items-center justify-center text-center">
                <div className="text-xs font-medium text-slate-400 mb-1">
                  {transfer.distanceKm} km transit • Est. saving: <strong className="text-emerald-400">{transfer.costSavingsEst}</strong>
                </div>
                <div className="flex items-center gap-2 text-blue-400">
                  <span className="w-12 h-0.5 bg-blue-700"></span>
                  <Truck className="w-5 h-5" />
                  <span className="w-12 h-0.5 bg-blue-700"></span>
                </div>
              </div>

              <div className="md:text-right">
                <div className="text-[11px] uppercase tracking-wider text-slate-500 font-semibold">Destination Depot (Deficit)</div>
                <div className="text-sm font-semibold text-slate-200 mt-1">{transfer.destinationFacility}</div>
              </div>
            </div>

            {/* Quantity and Medicine */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-2">
              <div>
                <div className="text-xs text-slate-400">Essential Drug & Quantity:</div>
                <div className="text-base font-bold text-slate-100 mt-0.5">
                  {transfer.item} —{' '}
                  <span className="text-emerald-400">
                    {transfer.quantity.toLocaleString()} {transfer.unit}
                  </span>
                </div>
              </div>

              {transfer.status === 'PENDING_APPROVAL' ? (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => handleReject(transfer.id)}
                    className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold rounded-lg border border-slate-700 transition-colors"
                  >
                    Reject Transfer
                  </button>
                  <button
                    type="button"
                    onClick={() => handleApprove(transfer.id)}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5 shadow-sm"
                  >
                    <CheckCircle2 className="w-4 h-4" />
                    Approve Inter-State Transfer
                  </button>
                </div>
              ) : (
                <div className="text-xs text-slate-400">
                  Action recorded: <strong className="text-slate-200">{transfer.approvedBy || transfer.status}</strong>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
